"""Report generation utilities for Proto v3."""
from django.utils import timezone
from django.db.models import Sum
import io
import datetime


def generate_daily_report(day_session):
    """Generate a daily report PDF for the given DaySession. Returns file path."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors
        import os
        from django.conf import settings

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        story.append(Paragraph(f"Proto v3 - Daily Report", styles['Title']))
        story.append(Paragraph(f"{day_session.shop.name} - {day_session.date}", styles['Heading2']))
        story.append(Spacer(1, 12))

        data = [
            ['Metric', 'Amount'],
            ['Total Transactions', str(day_session.total_transactions)],
            ['Total Sales', f"TSh {day_session.total_sales:,.0f}"],
            ['Cash', f"TSh {day_session.total_cash:,.0f}"],
            ['M-Pesa', f"TSh {day_session.total_mpesa:,.0f}"],
            ['Credit Issued', f"TSh {day_session.total_credit:,.0f}"],
            ['Net Profit', f"TSh {day_session.gross_profit:,.0f}"],
        ]
        t = Table(data, colWidths=[250, 200])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6146c1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7f7f8')]),
        ]))
        story.append(t)
        story.append(Spacer(1, 12))
        story.append(Paragraph(f"Generated by Proto v3 at {timezone.now().strftime('%Y-%m-%d %H:%M')}", styles['Small']))

        doc.build(story)
        buf.seek(0)

        report_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
        os.makedirs(report_dir, exist_ok=True)
        path = os.path.join(report_dir, f"daily_{day_session.shop.id}_{day_session.date}.pdf")
        with open(path, 'wb') as f:
            f.write(buf.read())
        return path
    except ImportError:
        return None


def send_daily_report(day_session, pdf_path):
    """Send the daily report to the owner via WhatsApp and/or email."""
    from settings_app.models import ShopSettings
    try:
        shop_settings = ShopSettings.objects.get(shop=day_session.shop)
    except ShopSettings.DoesNotExist:
        return

    if not shop_settings.daily_report_enabled:
        return

    results = []

    # ── WhatsApp ─────────────────────────────────────────────────
    wa_number = shop_settings.daily_report_whatsapp
    if wa_number:
        try:
            from whatsapp.providers import send_whatsapp
            from whatsapp.messages import daily_report_message
            # Build public URL for PDF if available (Twilio fetches media by URL)
            pdf_url = None
            if pdf_path:
                from django.conf import settings as dj_s
                media_root = getattr(dj_s, 'MEDIA_ROOT', '')
                media_url  = getattr(dj_s, 'MEDIA_URL', '/media/')
                site_url   = getattr(dj_s, 'SITE_URL', '')
                if media_root and pdf_path.startswith(media_root):
                    relative = pdf_path[len(media_root):]
                    if site_url:
                        pdf_url = site_url.rstrip('/') + media_url + relative.lstrip('/')
            message, media = daily_report_message(day_session, pdf_url)
            result = send_whatsapp(wa_number, message, media)
            results.append(('whatsapp', result))
            if not result.get('success'):
                import logging
                logging.getLogger('proto_v3').warning(
                    f"WhatsApp daily report failed: {result.get('error')}")
        except Exception as e:
            import logging
            logging.getLogger('proto_v3').error(f"WhatsApp daily report error: {e}")

    # ── Email ────────────────────────────────────────────────────
    email = shop_settings.daily_report_email
    if email and pdf_path:
        try:
            from django.core.mail import EmailMessage
            mail = EmailMessage(
                subject=f"Daily Report - {day_session.shop.name} {day_session.date}",
                body=f"Please find the daily report for {day_session.shop.name} attached.",
                to=[email],
            )
            with open(pdf_path, 'rb') as f:
                mail.attach(f"report_{day_session.date}.pdf", f.read(), 'application/pdf')
            mail.send()
            results.append(('email', {'success': True}))
        except Exception as e:
            import logging
            logging.getLogger('proto_v3').error(f"Email daily report error: {e}")

    return results


def generate_report_pdf(shop, start, end):
    """Generate a date-range report PDF and return bytes."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from django.conf import settings

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4)
        styles = getSampleStyleSheet()
        story = [
            Paragraph(f"Proto v3 - Sales Report", styles['Title']),
            Paragraph(f"{shop.name} | {start} to {end}", styles['Heading2']),
            Spacer(1, 20),
            Paragraph("Full detailed report. Configure report sections as needed.", styles['Normal']),
        ]
        doc.build(story)
        buf.seek(0)
        return buf.read()
    except ImportError:
        return b''