"""Report generation utilities for Proto v3."""
from django.utils import timezone
from django.db.models import Sum
import io
import datetime


def generate_daily_report(day_session):
    """Generate a daily report PDF for the given DaySession. Returns file path."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors
        import os
        from django.conf import settings

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        story.append(Paragraph(f"Proto v3 - Daily Report", styles['Title']))
        story.append(Paragraph(f"{day_session.shop.name} - {day_session.date}", styles['Heading2']))
        story.append(Spacer(1, 12))

        data = [
            ['Metric', 'Amount'],
            ['Total Transactions', str(day_session.total_transactions)],
            ['Total Sales', f"TSh {day_session.total_sales:,.0f}"],
            ['Cash', f"TSh {day_session.total_cash:,.0f}"],
            ['M-Pesa', f"TSh {day_session.total_mpesa:,.0f}"],
            ['Credit Issued', f"TSh {day_session.total_credit:,.0f}"],
            ['Net Profit', f"TSh {day_session.gross_profit:,.0f}"],
        ]
        t = Table(data, colWidths=[250, 200])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6146c1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7f7f8')]),
        ]))
        story.append(t)
        story.append(Spacer(1, 12))
        story.append(Paragraph(f"Generated by Proto v3 at {timezone.now().strftime('%Y-%m-%d %H:%M')}", styles['Small']))

        doc.build(story)
        buf.seek(0)

        report_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
        os.makedirs(report_dir, exist_ok=True)
        path = os.path.join(report_dir, f"daily_{day_session.shop.id}_{day_session.date}.pdf")
        with open(path, 'wb') as f:
            f.write(buf.read())
        return path
    except ImportError:
        return None


def send_daily_report(day_session, pdf_path):
    """Send the daily report to the owner via email. Extend for WhatsApp."""
    # Email sending - configure SMTP in settings for production
    # from django.core.mail import EmailMessage
    # email = EmailMessage(...)
    # email.send()
    pass


def generate_report_pdf(shop, start, end):
    """Generate a date-range report PDF and return bytes."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from django.conf import settings

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4)
        styles = getSampleStyleSheet()
        story = [
            Paragraph(f"Proto v3 - Sales Report", styles['Title']),
            Paragraph(f"{shop.name} | {start} to {end}", styles['Heading2']),
            Spacer(1, 20),
            Paragraph("Full detailed report. Configure report sections as needed.", styles['Normal']),
        ]
        doc.build(story)
        buf.seek(0)
        return buf.read()
    except ImportError:
        return b''
