# Generated by Django 6.0.3 on 2026-03-21 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='TSh', max_length=10)),
                ('language', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tax_name', models.CharField(default='VAT', max_length=20)),
                ('tax_inclusive', models.BooleanField(default=True)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('auto_reorder', models.BooleanField(default=False)),
                ('require_customer_on_credit', models.BooleanField(default=True)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('print_receipt_auto', models.BooleanField(default=False)),
                ('daily_report_enabled', models.BooleanField(default=True)),
                ('daily_report_time', models.TimeField(default='22:00')),
                ('daily_report_email', models.EmailField(blank=True, max_length=254)),
                ('daily_report_whatsapp', models.CharField(blank=True, max_length=20)),
                ('receipt_header', models.TextField(blank=True, help_text='Text shown at top of receipt')),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for shopping with us!')),
                ('show_tax_on_receipt', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='shops.shop')),
            ],
            options={
                'verbose_name_plural': 'shop settings',
            },
        ),
    ]
