# Generated by Django 6.0.3 on 2026-03-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='e.g. Piece, Kg, Litre, Packet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='units.unitofmeasure', verbose_name='Unit of Measure'),
        ),
    ]
